import { Geist, Geist_Mono } from "next/font/google";
import "@/style/globals.css";
import NavBar from "./components/NavBar";
import { UserProvider } from "./context/UserContext";
import Footer from "./components/Footer";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
			<body className="antialiased flex flex-col min-h-screen bg-main">
				<UserProvider>
					<header>
						<NavBar />
					</header>

					<main className="flex-1 px-4 py-6 max-w-6xl mx-auto w-full">
						{children}
					</main>
				</UserProvider>
				<Footer />
			</body>
		</html>
	);
}
